### ISSUE TITLE
missing shared_data_dir

### ISSUE THREAD

**Issue by cxwx** [Freed-Wu/zsh-rime#1]
编译的时候修改了 路径 ${HOME}/software/im/librime/rime-a1c8144-macOS-universal/dist/
但是安装时候 显示 missing shared_data_dir
```
source ~/software/im/zsh-rime/zsh-rime.plugin.zsh
missing shared_data_dir%
```

**Comment by Freed-Wu** [comment]
be default, it search shared_data_dir by:

- $PREFIX/share/rime-data
- if your $SHELL is /foobar/bin/sh, search /foobar/share/rime-data and /foobar/usr/share/rime-data
- /sdcard/rime-data
- /run/current-system/sw/share/rime-data

You can assign PREFIX, check $SHELL, or directly use zstyle

zstyle ':rime:traits' share_data_dir /foobar/share/rime-data
